%YAML 1.2
---

- text: |-
    【広告】
    みなさん、俺タワーって知ってますか……？
    そうです、私が出てるゲームです！

    俺タワーはブラウザ版が終了した後、「毎日こつこつ俺タワー」として細々とスマホで活動していました。
    ……が！今は違います！

    大型リニューアルを経て、前俺タワーのゲームシステムに、こつタワーで培ったおもしろストーリー、そしてちびキャラが加わりました！
    魅力的な要素はたくさんあります！ぜひ遊んでみてください！

    ?[Android版](https://play.google.com/store/apps/details?id=jp.co.semo.olasma) / ?[iOS版](https://apps.apple.com/jp/app/%E6%AF%8E%E6%97%A5%E3%81%93%E3%81%A4%E3%81%93%E3%81%A4%E4%BF%BA%E3%82%BF%E3%83%AF%E3%83%BC/id1171064884) / ?[DMM版](https://games.dmm.com/detail/olesma)
    
    #毎日こつこつ #俺タワー
  
  fileIds:
    - "618bc826e762b30789d59dcd"
    - "618bc900e762b30789d59dec"
    - "618bcb47e762b30789d59e0a"
    - "618bcb9ce762b30789d59e0b"

- text: |-
    【広告】
    毎日こつこつ俺タワーは毎週更新！
    前編・後編に分けて1週ずつ、計2週のイベントが行われています！
    
    最近は、
    ①ヤードポンド法について学んだり
    ②5周年を祝ってライブをしたり
    ③鮭の切り身と戦ったり
    ④カレーを作ったりしてます！

    いつもドタバタ大騒ぎ、だけどちょっとためになる？
    そんな毎日こつこつ俺タワー、ぜひ遊んでみてくださいね！

    ?[Android版](https://play.google.com/store/apps/details?id=jp.co.semo.olasma) / ?[iOS版](https://apps.apple.com/jp/app/%E6%AF%8E%E6%97%A5%E3%81%93%E3%81%A4%E3%81%93%E3%81%A4%E4%BF%BA%E3%82%BF%E3%83%AF%E3%83%BC/id1171064884) / ?[DMM版](https://games.dmm.com/detail/olesma)
    
    #毎日こつこつ #俺タワー
  
  fileIds:
    - "628f24e5995247bdc84714cc",
    - "628f24eb995247bdc84714cd",
    - "628f24f2995247bdc84714ce",
    - "628f24f5995247bdc84714cf"